import type { Metadata } from "next";
import { Kulim_Park } from "next/font/google";
import "./globals.css";
import { Logo } from "./Logo";

const kulimPark = Kulim_Park({
  variable: "--font-kulim-park",
  subsets: ["latin"],
  weight: ["200", "300", "400", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${kulimPark.variable} bg-gray-950 font-[family-name:var(--font-kulim-park)] text-gray-300 antialiased`}
      >
        <header className="flex justify-center p-4 text-center text-white">
          <div className="flex items-center gap-2 text-lg">
            <Logo />
            EditEase
          </div>
        </header>

        <main className="mt-4">{children}</main>
      </body>
    </html>
  );
}
